### ISSUE TITLE
pack build/**/*.class files in a JAR?

### ISSUE THREAD

**Issue by danmbox** [wandora-team/wandora#2]
Hi, I have noticed that the build folder of the wandora distribution contains unpacked .class files (and takes up a couple of hundred megabytes). These are usually kept in a JAR...

**Comment by akivela** [comment]
Hi Dan. Thanks for your message. You are right. Usually class files are packed into JARs. We have not packed Wandora's classes into a JAR because the application dynamically reads available class (and other resource) files with Java's class loader -- and we haven't yet figured out how to easily access resources in JAR files. If you have a working example in your mind, please, share. I have to admit that putting classes (and other resource) into a JAR would shrink the size of our distribution packages significantly.

**Comment by akivela** [comment]
Hi Dan et all

Finally Wandora can scan classes in JAR packages and we have changed the packaging mechanism of Wandora application. Once the application is built, Netbeans creates a complete distribution package in 'dist' folder and all Wandora classes are stored in JAR file 'lib/wandora.jar'. Other resources, including UI images, still locate in separate files in 'resources' folder.
