### ISSUE TITLE
Failed to build with ant

### ISSUE THREAD

**Issue by Yunlong-He** [wandora-team/wandora#7]
after cloned, I want to build wandora, but failed

Here is some log
====================================
   [javac]   符号:   变量 Platform
    [javac]   位置: 类 TextHTML.FXHTML
    [javac] /home/hyl/repo/nlp/wandora/src/org/wandora/application/gui/previews/formats/TextHTML.java:765: 错误: 找不到符号
    [javac]             Platform.runLater(new Runnable() {
    [javac]             ^
    [javac]   符号:   变量 Platform
    [javac]   位置: 类 TextHTML.FXHTML
    [javac] /home/hyl/repo/nlp/wandora/src/org/wandora/application/gui/previews/formats/TextHTML.java:795: 错误: 找不到符号
    [javac]                 Platform.runLater(runner);
    [javac]                 ^
    [javac]   符号:   变量 Platform
    [javac]   位置: 类 TextHTML.FXHTML
    [javac] /home/hyl/repo/nlp/wandora/src/org/wandora/application/gui/previews/formats/TextHTML.java:850: 错误: 找不到符号
    [javac]                         Platform.runLater(new Runnable() {
    [javac]                         ^
    [javac]   符号:   变量 Platform
    [javac]   位置: 类 TextHTML
    [javac] /home/hyl/repo/nlp/wandora/src/org/wandora/application/gui/previews/formats/VideoMp4.java:73: 错误: 找不到符号
    [javac]         Platform.setImplicitExit(false);
    [javac]         ^
    [javac]   符号:   变量 Platform
    [javac]   位置: 类 VideoMp4
    [javac] /home/hyl/repo/nlp/wandora/src/org/wandora/application/gui/previews/formats/VideoMp4.java:81: 错误: 找不到符号
    [javac]         fxPanel = new JFXPanel();
    [javac]                       ^
    [javac]   符号:   类 JFXPanel
    [javac]   位置: 类 VideoMp4
    [javac] 注: 某些输入文件使用或覆盖了已过时的 API。
    [javac] 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    [javac] 注: 某些输入文件使用了未经检查或不安全的操作。
    [javac] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    [javac] 注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出
    [javac] 100 个错误

BUILD FAILED
/home/hyl/repo/nlp/wandora/nbproject/build-impl.xml:985: The following error occurred while executing this line:
/home/hyl/repo/nlp/wandora/nbproject/build-impl.xml:281: Compile failed; see the compiler error output for details.

BTW, why not support building with maven? and there is no documentation for building from source

**Comment by akivela** [comment]
I think your build fails because you don't have Java FX libraries included in your Java installation. Are you using OpenJDK? I recall, it doesn't include Java FX by default. I suggest you try Oracle's Java JDK 8.x.

I not personally familiar with Maven as a build tool. If you would like to write instructions on building Wandora with Maven, I am more than happy to include the instructions to Wandora's documentation.

The short developer introduction tells we use Netbeans application to develop Wandora. The Netbeans project file is included in the Git repository.
